// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/agent.ts";
import * as $1 from "./routes/api/init.ts";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/systems/[symbol].tsx";
import * as $4 from "./routes/systems/index.tsx";
import * as $$0 from "./islands/NavLink.tsx";
import * as $$1 from "./islands/StarChart.tsx";
import * as $$2 from "./islands/StarChartD3Old.tsx";
import * as $$3 from "./islands/StarChartItem.tsx";
import * as $$4 from "./islands/StarChartOld.tsx";

const manifest = {
  routes: {
    "./routes/api/agent.ts": $0,
    "./routes/api/init.ts": $1,
    "./routes/index.tsx": $2,
    "./routes/systems/[symbol].tsx": $3,
    "./routes/systems/index.tsx": $4,
  },
  islands: {
    "./islands/NavLink.tsx": $$0,
    "./islands/StarChart.tsx": $$1,
    "./islands/StarChartD3Old.tsx": $$2,
    "./islands/StarChartItem.tsx": $$3,
    "./islands/StarChartOld.tsx": $$4,
  },
  baseUrl: import.meta.url,
};

export default manifest;
